# Generated by Django 4.0.3 on 2022-03-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
