# Generated by Django 4.0.3 on 2022-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_polygon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
